spring:
  application:
    name: CineMille
  datasource:
    url: jdbc:mysql://localhost:3306/cinemamille?useSSL=false&serverTimezone=UTC  # URL per MySQL
    username: root  # Nome utente MySQL
    password: Ade170993ade.  # La tua password per MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver  # Driver MySQL
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
server:
  port: 8080